// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9F0iy4dZag8SF0qg8vuNfPDUSTuerFeQ',
    appId: '1:824538877301:web:94eefd90b4ac381414573c',
    messagingSenderId: '824538877301',
    projectId: 'chat-app-a43e8',
    authDomain: 'chat-app-a43e8.firebaseapp.com',
    storageBucket: 'chat-app-a43e8.appspot.com',
    measurementId: 'G-XS2Q550T9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuYLHmusEU-BH_6mpk5znOxW8me6Wyt8k',
    appId: '1:824538877301:android:1eb49c92bbcc76d714573c',
    messagingSenderId: '824538877301',
    projectId: 'chat-app-a43e8',
    storageBucket: 'chat-app-a43e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBo8nmaNUAIxSb8bbDSi0OtSKAwBHbAY',
    appId: '1:824538877301:ios:ba41f3b63a98d7b014573c',
    messagingSenderId: '824538877301',
    projectId: 'chat-app-a43e8',
    storageBucket: 'chat-app-a43e8.appspot.com',
    iosClientId: '824538877301-0t363jfpgmdmsj73gulln5qhhm7custq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLBo8nmaNUAIxSb8bbDSi0OtSKAwBHbAY',
    appId: '1:824538877301:ios:83b84918b0758e2a14573c',
    messagingSenderId: '824538877301',
    projectId: 'chat-app-a43e8',
    storageBucket: 'chat-app-a43e8.appspot.com',
    iosClientId: '824538877301-89e5ilrb7991b1ochrvhhaiqjrno15ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
